// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Waldwunder")]
	public class Waldwunder
	{
		[Column("id"         ,IsIdentity =true, IsPrimaryKey = true)] public long     Id          { get; set; } // integer
		[Column("name"                            )] public string?  Name        { get; set; } // text(max)
		[Column("description"                     )] public string?  Description { get; set; } // text(max)
		[Column("province"                        )] public string?  Province    { get; set; } // text(max)
		[Column("latitude"                        )] public decimal? Latitude    { get; set; } // numeric
		[Column("longitude"                       )] public decimal? Longitude   { get; set; } // numeric
		[Column("type"                            )] public string?  Type        { get; set; } // text(max)
		[Column("votes"                           )] public decimal? Votes       { get; set; } // numeric

		#region Associations
		/// <summary>
		/// FK_Bilder_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Bilder.Wonder))]
		public IEnumerable<Bilder> Bilders { get; set; } = null!;
		#endregion
	}
}
