// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class SubwayDb : DataConnection
	{
		public SubwayDb()
		{
			InitDataContext();
		}

		public SubwayDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public SubwayDb(DataOptions<SubwayDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Stationen>    Stationens    => this.GetTable<Stationen>();
		public ITable<Verbindungen> Verbindungens => this.GetTable<Verbindungen>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Stationen? Find(this ITable<Stationen> table, long id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Stationen?> FindAsync(this ITable<Stationen> table, long id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static Verbindungen? Find(this ITable<Verbindungen> table, long id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Verbindungen?> FindAsync(this ITable<Verbindungen> table, long id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
