// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Verbindungen")]
	public class Verbindungen
	{
		[Column("Id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long Id              { get; set; } // integer
		[Column("VonId"                                                                                            )] public long VonId           { get; set; } // integer
		[Column("NachId"                                                                                           )] public long NachId          { get; set; } // integer
		[Column("FahrzeitMinuten"                                                                                  )] public long FahrzeitMinuten { get; set; } // integer
		[Column("IsBidirectional"                                                                                  )] public long IsBidirectional { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_Verbindungen_0_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(NachId), OtherKey = nameof(Stationen.Id))]
		public Stationen Nach { get; set; } = null!;

		/// <summary>
		/// FK_Verbindungen_1_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(VonId), OtherKey = nameof(Stationen.Id))]
		public Stationen Von { get; set; } = null!;
		#endregion
	}
}
